#pragma once
#include "Pinata/Core/Application.h"
#include "Pinata/Core/Log.h"
#include "Pinata/Core/Layer.h"
#include "Pinata/ImGui/ImGuiLayer.h"
#include "Pinata/Core/Input.h"
#include "Pinata/Core/KeyCode.h"
#include "Pinata/Core/MouseCode.h"
//--------entry point-----------------
#include "Pinata/Core/EntryPoint.h"